### ISSUE TITLE
Add Meta tags and Favicon and footer 

### ISSUE THREAD

**Issue by altafshaikh** [altafshaikh/make-your-first-contribution#26]
## Add Meta tags in the index.html
- meta keywords
- meta description

## Favicon in the index.html
- favicon icon related to development or open source

## Add Footer
- simple footer with copyright symbol

**Comment by Vidyart29** [comment]
I'll do this task

**Comment by altafshaikh** [comment]
okay

**Comment by mitishaa** [comment]
I will do this task.

**Comment by krshn-ptl** [comment]
Is this issue still open? May I work on this?

**Comment by Vidyart29** [comment]
Yes, You work on this issue, as I'm not able to fit it into my Schedule, I am aborting it.

**Comment by zorione** [comment]
May I work on this?

**Comment by krshn-ptl** [comment]
> May I work on this?

Actually, I have already completed and issued the PR. If the maintainer wants then you may

**Comment by altafshaikh** [comment]
sorry its already done @zorione

**Comment by altafshaikh** [comment]
@zorione if u have any idea to enhance this repository you can make an issue describing the feature and you can start working on it :)
